export interface PalletType{
    id? : Number,
    name? : String,
    type? : String,
    codification? : Number,
    app? : String,
    materialType? : String,
    color? : String,
    currency? : String,
    recordStatus? : Number,
    length? : Number,
    lengthType? : String,
    width? : Number,
    widthType? : String,
    height? : Number,
    heightType? : String,
    weight? : Number,
    weightType? :String,
    price? : Number,
    remark? : String,
    isPacking? : Number,
    isCarryIn? : Number,
    isCarryOut? : Number,
    isRunOut? : Number,
    createdTimestamp? : String,
    updatedTimestamp? : String,
}